### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by robisback** [datasets/covid-19#105]
It seems that the update got stuck on Oct 17th
Could you please solve this problem?

Thank you!

**Comment by sglavoie** [comment]
Hi @robisback, thanks for letting us know! We are looking into this issue and will report back as soon as a fix has been included. :+1:

**Comment by aminoplis** [comment]
I'll be waiting too. Thanks in advance

**Comment by gerrygeko** [comment]
My app got stuck too, so I hope this get fixed quite soon

**Comment by sglavoie** [comment]
**FIXED**: Closing, this issue was taken care of in commit adc88e327e01d1bafff75c61eee2759e4445dd20.
