### ISSUE TITLE
No data for 2021

### ISSUE THREAD

**Issue by matthysk** [datasets/covid-19#115]
Hi,

There is no data for 2021 in the dataset.

This is available in the upstream repo, so somehow it is not being merged.

Best regards,

**Comment by sglavoie** [comment]
Hi @matthysk,

Could you explain the issue you are facing a bit further? At this time, all the CSV files contain data up to yesterday: https://github.com/datasets/covid-19/tree/main/data.

**Comment by matthysk** [comment]
Hi @sglavoie,

My mistake, I was using the "master" branch instead of branch "main".

It may be a good idea to mention in the README that the most up to date branch is "main".

Thanks for this excellent resource.

Best regards,

**Comment by sglavoie** [comment]
Great to hear it works! :smile: I deleted the `master` branch to avoid confusion in the future as the default branch was set to `main` at the beginning of this year and `master` is no longer being kept up-to-date.

Thank you for reporting the issue :slightly_smiling_face:.
