### ISSUE TITLE
Add graphs to data package so they show up on datahub.io 

### ISSUE THREAD

**Issue by rufuspollock** [datasets/covid-19#19]
When viewing https://datahub.io/core/covid-19 i want to see summary graphs so that a) i get an immediate overview b) i get a sense of what's in the dataset

## Tasks

* [x] Add basic graph of total world to date = sum across all for each date
* [x] Add key countries e.g. China, US, Italy, UK, France and Germany. Have to sum across provinces for a given country e.g. china

**Comment by rufuspollock** [comment]
Basic graph is up for total worldwide https://github.com/datasets/covid-19 - though not yet committed to the repo.

**Comment by anuveyatsu** [comment]
FIXED, see the second graph here - https://datahub.io/core/covid-19

Screenshot:

<img width="1136" alt="Screen Shot 2020-03-24 at 20 06 30" src="https://user-images.githubusercontent.com/17809581/77434398-fce7cf00-6e0a-11ea-9a2e-3ed29efaa293.png">
