### ISSUE TITLE
Italy has wrong data for March 23

### ISSUE THREAD

**Issue by deleugpn** [datasets/covid-19#31]
I was updating my dashboards on https://corona.deleu.dev and I noticed a full flat data on Italy.

The dataset shows 

```
2020-03-21,Italy,,43.0,12.0,53578,6072,4825
2020-03-22,Italy,,43.0,12.0,59138,7024,5476
2020-03-23,Italy,,43.0,12.0,59138,7024,5476
```

when in reality it should be 

```
2020-03-21,Italy,,43.0,12.0,53578,6072,4825
2020-03-22,Italy,,43.0,12.0,59138,7024,5476
2020-03-23,Italy,,43.0,12.0,63,927,7432,6077
```

**Comment by naveen-pit** [comment]
It seems `process.py` pointed to outdated version of files
`BASE_URL = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/'
CONFIRMED = 'time_series_19-covid-Confirmed.csv'
DEATH = 'time_series_19-covid-Deaths.csv'
RECOVERED = 'time_series_19-covid-Recovered.csv'`

Original sources has already [mentioned ](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series) that these files were outdated. Please reference `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` for the latest time series data.

**Comment by anuveyatsu** [comment]
Hi @deleugpn and @naveen-pit thanks for letting us know. We'll look into it.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datasets/covid-19/commit/0875bc923ec0f9d0e88ae6c36c5f9acefe727d29
