### ISSUE TITLE
time-series-19-covid-combined.csv much shorter today

### ISSUE THREAD

**Issue by tkubec** [datasets/covid-19#34]
Hi,,
the number of records of time-series-19-covid-combined.csv is approx half of yesterday count (31000 rows).
It seems some data are lost - or am I missing something? Thanks

**Comment by bryantloy** [comment]
Looks like today's set doesn't have state level breakouts for the US at a first glance.

**Comment by anuveyatsu** [comment]
@tkubec it must be due to change in the upstream repo, see the comment here https://github.com/datasets/covid-19/issues/31#issuecomment-603180504

**Comment by anuveyatsu** [comment]
@bryantloy is right, the updated data doesn't have state level breakouts for the US.

Closing this issue.
