### ISSUE TITLE
404 on the recovery url

### ISSUE THREAD

**Issue by ruivalmeida** [datasets/covid-19#40]
On running process.py, I get a 404 on the confirmed url. This one:
`RECOVERED = 'time_series_19-covid-Recovered.csv'`

Maybe this is just some temporary url bug, but I thought I'd let you know.

Meanwhile, I have managed to get the script to run by commenting out all references to the recovered portion of the data, which is less than ideal.

Great job!

**Comment by anuveyatsu** [comment]
hi @ruivalmeida thanks for reporting this. It was happening due to removal of "recovered" data in the upstream. We've now removed it as well. See https://github.com/datasets/covid-19/commit/b0f4726a22e4133d713ae8986e0a9f94becf7dbb
