### ISSUE TITLE
RECOVERED number seems to be available again at source, just under a new filename.

### ISSUE THREAD

**Issue by sgg70** [datasets/covid-19#43]
would it be possible to feed it back in?
see
("time_series_covid19_recovered_global.csv | update recoverd time series with 3/26/20 data")
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by anuveyatsu** [comment]
FIXED, see the commit above.

cc @sgg70
