### ISSUE TITLE
Inconsistent file formatting

### ISSUE THREAD

**Issue by CEsprey** [datasets/covid-19#44]
The data files have inconsistent file formatting making it difficult to write code which works on all files. 

Headers example: `Last Update` changes to `Last_Update`, `Confirmed` changes to `FIPS`.

Changes to Country/ Region: `UK` changes to `United Kingdom`.

 Compare files '02-03-2020.csv' to '03-26-2020.csv' for example.

**Comment by anuveyatsu** [comment]
hey @CEsprey I don't think your issue is related to this repo. We don't provide last update data and we don't have files you've mentioned.

**Comment by CEsprey** [comment]
Oh weird, my bad!

Stay safe 🙂
