### ISSUE TITLE
[workflow] Actions pipeline stucked

### ISSUE THREAD

**Issue by dennislwy** [datasets/covid-19#52]
Your action workflow seems stucked since 10 hours ago
Possible something gone wrong while at step `Run pip install -r scripts/requirements.txt`

![image](https://user-images.githubusercontent.com/5407099/78521534-bcba2080-77fc-11ea-98e6-36918fcf9e74.png)

![image](https://user-images.githubusercontent.com/5407099/78521607-fbe87180-77fc-11ea-8fe5-259b4837ff63.png)

**Comment by anuveyatsu** [comment]
FIXED see the last build.
