### ISSUE TITLE
Admin2/City field missing in US data

### ISSUE THREAD

**Issue by kennymalac** [datasets/covid-19#58]
Since the following commit: https://github.com/datasets/covid-19/commit/ab35560715893c58daa64e2e8dc8553b3fc1c3f1
The "Admin2" field is missing from US CSV files. In my case, I was using this field to filter data by US city, and now I can only do so by state. Can this field be added back into the US datasets?

**Comment by anuveyatsu** [comment]
hey @kennymalac it should be back now

**Comment by kennymalac** [comment]
Thanks
