### ISSUE TITLE
France aggregated count is down from yesterday, why?

### ISSUE THREAD

**Issue by efaysal** [datasets/covid-19#63]
France count or confirmed number has an issue, 
82 2020-04-12 133670
83 2020-04-13 137875
84 2020-04-14 131361
why the number is going down from yesterday?
As it is an aggregated number is has to growth or to show stagnation ... 
Thank for any clarification.

**Comment by anuveyatsu** [comment]
@efaysal yes, these are cumulative figures and must not decrease. This must be a mistake in the upstream and hopefully will be corrected anytime soon.

**Comment by efaysal** [comment]
It is very surprising that the processing is not making a check on this kind of issue. A simple check in the code as if last is greater than the next, stop to fix!  

I guess the problem may be related to France territories, main land is in Europe and the territories are scattered in pacific and America  and so on. Counting  over all territories, something is not making sense ... 

However, the counts related to other countries make sense to me:
Some numerical results are in
https://www.linkedin.com/posts/faysal-el-khettabi-ph-d-4847415_covid19-activity-6656209189657997313-9F2k

**Comment by anuveyatsu** [comment]
@efaysal this project doesn't do any data modification but standardization/normalization if possible. We also can add more metadata etc.

**Comment by anuveyatsu** [comment]
Btw, France data was corrected recently - https://github.com/datasets/covid-19/commit/bed2cbaeccabece8ae86e15363cfc910afdbddb2

**Comment by anuveyatsu** [comment]
FIXED:

```
2020-04-13,France,125394,28001,14986
2020-04-14,France,131361,29098,15748
2020-04-15,France,134582,31470,17188
```
