### ISSUE TITLE
France cumulative numbers are down Again

### ISSUE THREAD

**Issue by efaysal** [datasets/covid-19#71]
2020-04-20 156480
2020-04-21 159297
2020-04-22 157125

**Comment by anuveyatsu** [comment]
hey @efaysal please check the issues in https://github.com/CSSEGISandData/COVID-19/issues I'm sure it is tracked there already. We can't/won't fix this sort of issues as we are not generating the data but processing/cleaning/normalizing etc.

**Comment by efaysal** [comment]
Thank you @anuveyatsu . I will close then this issue.
