### ISSUE TITLE
No update since April 23rd?

### ISSUE THREAD

**Issue by coder-amey** [datasets/covid-19#72]
The data doesn't seem to have been updated after 2020-04-23.

**Comment by tomo-one** [comment]
JHU changes the update frequency on 23rd of April (see https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/README.md). I think the maintainer(s) will change it soon. Their script runs a little bit before the update. Maybe fixed soon...

**Comment by anuveyatsu** [comment]
It's updated between 6 and 7 AM GMT+0
We also run the script every 6h to pull any fixes/changes.

**Comment by coder-amey** [comment]
Thanks for the clarification.
