### ISSUE TITLE
No update since April 24rd?

### ISSUE THREAD

**Issue by zomorrod2020** [datasets/covid-19#73]
hi, The data doesn't seem to have been updated after 2020-04-24. 
JHU site is updated to 25-4-2020 but data in here no!
also yesterday we had same problem.
thanks

**Comment by anuveyatsu** [comment]
@zomorrod2020 it should be updated at around 6AM GMT+0, however, sometimes github actions fail. We're investigating why it happens. In the meantime, we're trying to update the data without the worker which means it is not updated at exact time but around 4-6AM GMT+0.

**Comment by sglavoie** [comment]
**FIXED**: Closing as the workflow was updated in https://github.com/datasets/covid-19/commit/16b7af9357ed7d881a05d2b3005cd93f208b563f to fix the latest issues. It will still tend to fail from time to time, but updates are coming in on a daily basis, which is good enough to be useful for now.
