### ISSUE TITLE
set github actions to execute every one or two hours

### ISSUE THREAD

**Issue by zomorrod2020** [datasets/covid-19#75]
hi,
please set github actions to execute every one or two hours. because most of them will failed!

**Comment by sglavoie** [comment]
@zomorrod2020, thank you for the suggestion. However, the problem that's happening here is that too much processing is being done in our current implementation and this is about an optimization issue, not per se related to GitHub Actions. We are working on a solution.

I am closing this issue as no actions need to be taken regarding GitHub Actions (our sources do not update frequently enough to require such measure to be applied). Thank you for flagging this unintended consequence, though. A fix is on the way. :slightly_smiling_face:
