### ISSUE TITLE
Countries aggregated CSV did not update this morning

### ISSUE THREAD

**Issue by dannyreed** [datasets/covid-19#79]
Up until today this CSV was updating daily in the morning PST: https://github.com/datasets/covid-19/blob/master/data/countries-aggregated.csv

It did not update today so far.

**Comment by sglavoie** [comment]
@dannyreed, thank you for letting us. We are reworking the way the data is generated to avoid those issues in the future.

I know this doesn't fully solve your issue, but [here is the updated data you are looking for](https://raw.githubusercontent.com/sglavoie/covid19-dataset/master/data/processed/countries-aggregated.csv). Hopefully we'll have this solved by tomorrow. :+1:

**Comment by dannyreed** [comment]
Perfect, thanks for the quick update.

**Comment by sglavoie** [comment]
@dannyreed, we haven't got the chance to finish working on this issue, but if you'll be needing updates specifically for "countries aggregated", you can temporarily use the data from the CSV I linked above: it's just been updated in case you need it. :+1:

**Comment by dannyreed** [comment]
Thanks! Heads up: Korea, South is not properly escaped this the updated CSV.

**Comment by sglavoie** [comment]
Thank you @dannyreed for spotting this. We were only retrieving the data without further processing. This should now be fixed in the linked version above and soon enough the changes should be reflected in this repo :wink:.

**Comment by rufuspollock** [comment]
FIXED. See previous comment.
