### ISSUE TITLE
如何下载csv文件？

### ISSUE THREAD

**Issue by little-olivia** [datasets/covid-19#81]

**Comment by mayaa6** [comment]
download or clone the entire repository

**Comment by sglavoie** [comment]
@little-olivia, if you are not familiar with GitHub, you can access the CSV files at the following links (open them and save them one by one on your computer):

* https://github.com/datasets/covid-19/raw/master/data/countries-aggregated.csv
* https://github.com/datasets/covid-19/raw/master/data/key-countries-pivoted.csv
* https://github.com/datasets/covid-19/raw/master/data/reference.csv
* https://github.com/datasets/covid-19/raw/master/data/time-series-19-covid-combined.csv
* https://github.com/datasets/covid-19/raw/master/data/us_confirmed.csv
* https://github.com/datasets/covid-19/raw/master/data/us_deaths.csv
* https://github.com/datasets/covid-19/raw/master/data/worldwide-aggregated.csv

The URLs should not change. You can also find the original source of the data here:
* https://github.com/CSSEGISandData/COVID-19
