### ISSUE TITLE
Source of India data

### ISSUE THREAD

**Issue by sabyasachipal** [datasets/covid-19#84]
It will be helpful if you can include the source of data correspond to India.

**Comment by sglavoie** [comment]
Hi @sabyasachipal!

The list of sources currently used by Johns Hopkins University Center for Systems Science and Engineering (CSSE) can be seen in their [repository](https://github.com/CSSEGISandData/COVID-19).

For India, they list the following source:

* India Ministry of Health and Family Welfare: https://www.mohfw.gov.in/

Thank you for pointing this out. An update shall come :wink:.
