### ISSUE TITLE
Data not updating

### ISSUE THREAD

**Issue by karansehgal1988** [datasets/covid-19#94]
Hello,
Data for countries-aggregated is not updating for past 9 days. Can you please look into this issue asap.
Thanks.

**Comment by Morisset** [comment]
It is possible to generate the tables locally on your own computer by running the following script:
https://raw.githubusercontent.com/datasets/covid-19/master/scripts/process.py
I did a fork of the repository and run the process script in it, then commit the new files, so on my fork the data are uptodate. I will try to run it everyday.
My fork is there: https://github.com/Morisset/covid-19

**Comment by sglavoie** [comment]
Thank you to both of you.

I'm closing this issue in favor of the existing one #91. The data has been updated manually for now, we'll be working on a fix.
